feat: accept bits account details uri
Informasjonsforvaltning/fdk-api-endpoints pull request #15
Opened 2021-09-14 10:36 UTC by NilsOveTen

resolves #14

2021-09-14 11:26 UTC, stigbd requested changes
Som du ser: my bad. Feil i spekk.

2021-09-14 11:26 UTC, stigbd commented on src/main/kotlin/no/fdk/endpoints/mapper/EndpointMappers.kt
> +private const val BITS_KONTOOPPLYSNINGER_URI = "https://bitsnorge.github.io/dsop-accounts-api/"
Min feil. Vi bør endre uri til `https://bitsnorge.github.io/dsop-accounts-api`, altså fjerne trailing slash.

2021-09-14 13:02 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/endpoints/mapper/EndpointMappers.kt
> +private const val BITS_KONTOOPPLYSNINGER_URI = "https://bitsnorge.github.io/dsop-accounts-api/"
2520454

2021-09-14 13:03 UTC, stigbd approved these changes

2021-09-15 06:40 UTC, matsjs approved these changes

2021-09-16 06:20 UTC, merged