Feat/not/jena mapper
Informasjonsforvaltning/fdk-api-endpoints pull request #3
Opened 2020-11-02 14:52 UTC by NilsOveTen

2020-11-02 15:00 UTC, valosnah requested changes

2020-11-02 15:00 UTC, valosnah commented on .github/workflows/deploy-demo.yaml
> +      - uses: actions/checkout@v1
v2

2020-11-02 15:00 UTC, valosnah commented on .github/workflows/deploy-demo.yaml
> +        uses: stefanprodan/kube-tools@v1
bytt uses: til run: | 
slett alt til og med "helm init"
Husk å indentere resten av commands et hakk inn

2020-11-02 15:00 UTC, valosnah commented on .github/workflows/deploy-prod.yaml
> +          version: '270.0.0'
dropp linjen med version

2020-11-02 15:00 UTC, valosnah commented on .github/workflows/deploy-prod.yaml
> +      - uses: actions/checkout@v1
v2

2020-11-02 15:00 UTC, valosnah commented on .github/workflows/deploy-prod.yaml
> +        uses: stefanprodan/kube-tools@v1
se tidligere kommentar om fjerning av kube-tools

2020-11-02 15:00 UTC, valosnah commented on .github/workflows/deploy-staging.yaml
> +          version: '270.0.0'
fjern linje med version

2020-11-02 15:00 UTC, valosnah commented on .github/workflows/deploy-staging.yaml
> +      - uses: actions/checkout@v1
v2

2020-11-02 15:00 UTC, valosnah commented on .github/workflows/deploy-staging.yaml
> +      - name: Apply Helm template
se tidligere kommentar om fjerning av kube-tools

2020-11-03 08:11 UTC, stigbd approved these changes
Har vi muligheit til å få opp coverage-stats i PR slik som feks python-baserte biblioteker?

2020-11-03 08:13 UTC, azaxarov requested changes

2020-11-03 08:13 UTC, azaxarov commented on src/main/kotlin/no/fdk/endpoints/controller/EndpointsController.kt
> +        @RequestParam(value = "environment", required = true) environment: String,
environment bør ikke være en del av request, men heller bestemmes fra config-fil

2020-11-03 10:50 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/endpoints/controller/EndpointsController.kt
> +        @RequestParam(value = "environment", required = true) environment: String,
Det er ikke hvilket miljø vi er på, men hvilken type miljø apiene dekker. Høsteren vår i prod kan ha feks ha api som både er test og production, dette parameteret sier om vi skal filtrere endepunktene etter test eller production.

Men vi hardkoder alt til 'test' i demo og staging, og alt til 'production' i prod. Dette er en midlertidig hack til vi har et rdf-felt vi kan vise hvilket miljø apiene tilhører. Frem til vi klarer å fikse det må vi være forsiktige med hvilke DSOP-api som høstes i prod

2020-11-03 10:59 UTC, azaxarov approved these changes

2020-11-03 12:17 UTC, merged